baseURL = 'https://davidgasquez.github.io/'
languageCode = 'en-us'
title = 'David Gasquez'

theme = 'PaperMod'

# Theme Settings
[params]
DateFormat = "January 2, 2006"
defaultTheme = "dark"
disableThemeToggle = true
images = ["avatar.jpg"]
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
env = "production"

[params.label]
text = "David Gasquez"

[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon.ico"
favicon32x32 = "favicon.ico"

[params.profileMode]
enabled = true
title = "David Gasquez"
subtitle = """
Learning about anything and everything all of the time.

Passionate about Data and Open Source.

Did some data stuff @protocollabs, @buffer.
"""
imageUrl = "avatar.jpg"
imageWidth = 250
imageHeight = 250
imageTitle = "Profile Picture"

[[params.profileMode.buttons]]
name = "Handbook"
url = "https://publish.obsidian.md/davidgasquez"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/davidgasquez/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/davidgasquez/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/davidgasquez/"

[[params.socialIcons]]
name = "email"
url = "mailto:davidgasquez@gmail.com"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/user/kalendos"

[params.cover]
hiddenInList = true
responsiveImages = true

[params.editPost]
URL = "https://github.com/davidgasquez/davidgasquez.github.io/content"
Text = "Suggest Changes"
appendFilePath = true

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts/"
weight = 10

[markup.highlight]
noClasses = false
